### ISSUE TITLE
Insufficient arguments passed to this XML-RPC method.

### ISSUE THREAD

**Issue by eduardodgarciac** [letrunghieu/wordpress-xmlrpc-client#26]
I am trying to make a new Post and it throws me this error "Insufficient arguments passed to this XML-RPC method."

`$wpClient = new WordpressClient($domain->url, $domain->user, $domain->password);`
`$wpClient->newPost('Tittle', 'Content');`

The getProfile method works fine, so there is no problem with the credentials

Can anyone help me with this?
Thanks in advance

**Comment by letrunghieu** [comment]
Which version of PHP do you use? There are some problems with PHP 7 that I am investigating.

**Comment by eduardodgarciac** [comment]
I'm using php 7. Oh I see... well, I'm breaking my head with that error

**Comment by letrunghieu** [comment]
The problem is fixed, you can `composer update` to get the latest version of this package. Please read the release note of the version 2.5.0 [here](https://github.com/letrunghieu/wordpress-xmlrpc-client/releases/tag/2.5.0)

**Comment by eduardodgarciac** [comment]
Thank you very much. I already tested and seems to works perfectly

**Comment by clmadrazo** [comment]
I have this same problem. Before upgrading to PHP7 I was working fine. I already upgraded to version 2.5 and I still have the same problem.

array(2) {
  ["faultCode"]=>
  int(400)
  ["faultString"]=>
  string(53) "Insufficient arguments passed to this XML-RPC method."
}
